# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week.
      interval: "weekly"

  # Enable version updates for UV.
  - package-ecosystem: "uv"
    # Look for `uv.lock` in the root directory.
    directory: "/"
    # Check PyPI once a week.
    schedule:
      interval: "weekly"
    # Group UV package updates together.
    groups:
      python-packages:
        patterns:
          - "*"
